services:
  - type: web
    name: wfm-power-planner
    env: python
    buildCommand: pip install -r requirements.txt && flask db upgrade
    startCommand: gunicorn run:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: SECRET_KEY
        generateValue: true
      - key: ICS_CALENDAR_URL
        sync: false
databases:
  - name: wfm_power_planner
    databaseName: wfm_power_planner
    user: hulkster